### PR TITLE
Add HeatQuickDeath Mod

### LINKED ISSUE #68: Setting: treat all non-completion Deaths as QuickRestarts
If a run is completed, Zag should spawn in the blood pool as normal. If the death occurs anywhere else, the game should act as if QuickRestart was triggered.

### PR DESCRIPTION
**Pull request by Zyruvias**
- Add HeatQuickDeathMod; treats normal deaths as if you emitted a "Quick Restart" input right before dying organically.
- Added HeatQuickDeath UI to QoL Menu

### CODE REVIEW

**Comment by Zyruvias** [comment]
Ignore all the closing/opening, I am new to managing PRs on GitHub specifically 😩

**Comment by cgu11** [comment]
poggers

**Comment by Zyruvias** [comment]
A couple of conversations I'd like to have about this specifically:

1) I originally intended this to be used with "HellModeToggle" on specifically so there's no benefit in any%, but does that really matter? I was thinking Personal Liability had to be on, but then again the lines get a bit blurry between high high heat and just like 50 heat speed pacts where not every aspect needs to run hell mode to have an optimal pact... thoughts?

2)  If this is added and can be used for any% / or any speedrunning contexts, does it matter if worst-case speedrunning situations are improved? E.g. dying in an all aspects run and skipping the house if you decide to continue on and redo the run anyway. I know that's such a small consideration but it might be worth acknowledging at the very least.

**Comment by Museus** [comment]
>     1. I originally intended this to be used with "HellModeToggle" on specifically so there's no benefit in any%, but does that really matter? I was thinking Personal Liability had to be on, but then again the lines get a bit blurry between high high heat and just like 50 heat speed pacts where not every aspect needs to run hell mode to have an optimal pact... thoughts?

I don't think there's any reason to restrict this to just High Heat. As long as it's not beneficial to the run itself, I don't mind it being a global feature. Will need to get community input though. Been a while since our last modpack poll.

>     2. If this is added and can be used for any% / or any speedrunning contexts, does it matter if worst-case speedrunning situations are improved? E.g. dying in an all aspects run and skipping the house if you decide to continue on and redo the run anyway. I know that's such a small consideration but it might be worth acknowledging at the very least.

I think that this will have to just be a banned situation. "If you have QuickDeath enabled, you cannot continue runs through a death." or "If you die with QuickDeath enabled, you must reset." or whatever is most clear.

Overall, everything looks good to me, so if y'all are cool with it I'll make a poll and depending on results we can merge it in for testing with the eventual rc4 stuff

**Comment by Zyruvias** [comment]
Where should that note be added? Also, I just now realized that I still have `HellModeToggle` in the credits... I may rename it to just `QuickDeath` in that case since there's really not a reason to only use it in heat.

I am fine with adding a poll. Feel free to do that whenever and I can clean this up a smidge before merging.

**Comment by Museus** [comment]
> Where should that note be added? 

Probably just in the rules, maybe add another line below the setting like "Must be deathless" or something so people at least have a hint that there's a condition, and can ask in the discord or check the rules

**Comment by Zyruvias** [comment]
Making some changes from Discord discussion: 

> Honestly might want to just merge it into QuickRestart, as an extra setting?

Merged in as `QuickRestart.QuickDeathEnabled` config setting.

> Just realized we override the HandleDeath function in QuickRestart, so if you do merge it into that, you should put it at the top of the override instead of wrapping it

Fixed, conditions simplified a little too.

**Comment by Museus** [comment]
```lua
OnAnyLoad{ "RoomPreRun",
    function ( triggerArgs )
        if QuickRestart.UsedQuickRestart then
            thread( PlayVoiceLines, GlobalVoiceLines.EnteredDeathAreaVoiceLines )
            QuickRestart.UsedQuickRestart = false

            -- Reset Starting Keepsake
            if QuickRestart.config.KeepStartingKeepsake and QuickRestart.StartingKeepsake ~= nil then
                DebugPrint({ Text="Setting keepsake trigger" })
                QuickRestart.TriggerKeepsakeChange = true
            end
        end
    end
}
```

This chunk is what sets the flag for resetting keepsake. With the simplified condition, this won't get set.

Instead, I'd recommend adding another if statement in at QuickRestart.lua:142 - after the 

```lua
if QuickRestart.UsedQuickRestart then
    RemoveInputBlock({ Name = "QuickRestart" })
end
```

that checks for QuickDeathEnabled and ClearedRun and sets "UsedQuickRestart", so the rest of the triggers get handled properly.

**Comment by Zyruvias** [comment]
Fixed, good catch... I totally goofed and assumed things would be fine after the simplification and no need to re-test in a code base that I'm just now getting my toes wet in...

**Comment by Museus** [comment]
Pushed out to v1.3.0

Issue set up to track at #68

**Pull request merged**
