### PR TITLE
Run Start Control + ModUtil Updates

### PR DESCRIPTION
**Pull request by cgu11**
This PR updates ModUtil to the latest version (only notable change is PathArray() to PathToIndexArray(), functionality *should* be identical, pending further testing.

Also adds RunStartControl and removes FixedHammers, to replace the hammer fixing part of the ruleset, and updates default rulesets/settings to match a hypothetical leaderboard legal instance of this.

Turned ModUtil and RunStartControl into submodules.

### CODE REVIEW

**Comment by bgallenstein** [comment]
Curious about the RunStartControl bit, but looks like its not a public repo on Museus' page?  Otherwise I have no comments.  I think you guys have full permissions, but let me know if you need anything

**Comment by ellomenop** [comment]
Curious about the RunStartControl bit, but looks like its not a public repo on Museus' page? Otherwise I have no comments. I think you guys have full permissions, but let me know if you need anything

**Comment by cgu11** [comment]
Yeah I didn’t have perms for some reason, despite being a collaborator, to make a branch, so I had to fork. We’ll make the repo public once it’s merged in I assume. Holding it here until we make a ruleset decision I think.

**Comment by cgu11** [comment]
@ellomenop RunStartControl has been made public if you want to check it out.

**Pull request merged**
